### ISSUE TITLE
Cannot terminate an externally created thread in IPCServer

### ISSUE THREAD

**Issue by ClementDoss** [Limagito/BackupOfCromis#3]
Hi,

I'm getting this error with Delphi 11
Project IPCServer.exe raised exception class EThread with message 'Cannot terminate an externally created thread'.

To reproduce I am compiling IPCServer using FastMM4 (external library, not the one included in Delphi).
Click start button, wait a few seconds and click stop button. This exception is raised.

Could you please tell me if this is an expected exception?
(Since you are not creating an external thread, I'm supposing there's some memory issue)

**Comment by CPsoftBE** [comment]
Hi, I'll upload the latest version of the files that I'm using in my application.

**Comment by CPsoftBE** [comment]
I'll upload my latest patches asap

**Comment by ClementDoss** [comment]
Thank you

**Comment by CPsoftBE** [comment]
Uploaded to Branch 'Limagito Patches'.
FYI I'm using FastMM5

**Comment by ClementDoss** [comment]
Hi,
Using branch 'Limagito Patches' solved the problem. I'm using FastMM4.

Thank you

**Comment by CPsoftBE** [comment]
Ok thank you Clement
